services:
  - type: web
    plan: free
    name: kifi-telegram-middleware
    runtime: image
    region: virginia
    image:
      url: docker.io/tradekifi/telegram-middleware:latest
    envVars:
      - key: PORT
        value: 3000
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
