# This is a basic example Blueprint for a Django web service and
# the Render Postgres database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: kifi-telegram-middleware
    runtime: image
    region: virginia
    healthCheckPath: /api/health
    image:
      url: docker.io/tradekifi/telegram-middleware:latest
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: JWT_SECRET
        generateValue: true
